config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  match '/home',       to: 'static_pages#home',    via: 'get'
  match '/about',      to: 'static_pages#about',   via: 'get'
  match '/signup',     to: 'users#new',            via: 'get'
  match '/signin',     to: 'sessions#new',         via: 'get'
  match '/signout',    to: 'sessions#destroy',     via: 'delete'
  match '/myconcerts', to: 'concerts#show',        via: 'get'
  match '/myartists',  to: 'artists#show',         via: 'get'

  
  resources :users,    only: [:create, :show]
  resources :artists,  only: [:new, :create, :index, :destroy]
  resources :sessions, only: [:create, :destroy]
  resources :concerts, only: [:new, :create, :index, :destroy]
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :user
  before_create :set_defaults
  
  validates :name, presence: true #, uniqueness: { case_sensitive: false }  
  validates :user_id, presence: true

  def set_defaults
    self.photo   ||= "http://i.imgur.com/Ha087R9.jpg?3"
    self.similar ||= "No similar artist listed."
  end

  def self.artist_info(artist)
    artist = URI.encode(artist)
    search_url = "http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=#{artist}&autocorrect[1]&api_key=0cf9f131e6c898341d48bf10b5488916&format=json"
    HTTParty.get search_url
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :signed_in_user
  
  def new
     @artist = Artist.new
  end

  def show
    @my_artists = current_user.artists  
  end

  def create 
    @artist = current_user.artists.build(artist_params)
    if @artist.save
      redirect_to myartists_path, notice: "You have created an artist"
    else
      render 'new'
    end
  end

  def index
    if params[:artist].blank?
      redirect_to new_artist_path
    else
      @artist = Artist.artist_info(params[:artist])
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to myartists_path, notice: "You have deleted a artist"
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :photo, :similar)
  end

  def signed_in_user
    redirect_to signin_path, notice: "Please sign in" unless signed_in?
  end

end 

app/helpers/artists_helper.rb
module ArtistsHelper
  
  def add_to_artists
    link_to "Add to My Artists", artists_path(artist_params), method: :post
  end
  

  def artist_params
    similar_name = @artist["artist"]["similar"].include?("artist") ? @artist["artist"]["similar"]["artist"][0]["name"] : " " 
    
    { artist: {
      name: @artist["artist"]["name"], photo: @artist["artist"]["image"][3]["#text"],
      similar: similar_name 
    } }
  end
end

app/views/artists/_results.html.erb
<h1><%= @artist["artist"]["name"] %></h1>
<%= image_tag(@artist["artist"] ["image"][4]["#text"]) %><br/>
<%= add_to_artists %>
<h1>Similar Artists:</h1>
<% if @artist["artist"]["similar"].include?("artist") %>
  <% @artist["artist"]["similar"]["artist"].each do |artist| %>
    <%= artist["name"] %><br/>
  <% end %>
<% else %>
  <h1>Similar Artists: no similar artists listed at this moment.</h1>
<% end %>
<h1><%= @artist["artist"]["bio"]["summary"].html_safe %></h1>

app/views/artists/index.html.erb
<img src="http://i.imgur.com/x2G2aLn.jpg" id="bg-list">
<% provide(:title, "Search Results") %>
<div class="artist-results"> 
  <% if @artist.include?("error") %>
    Sorry, there are no artists listed with that name. 
    <br/><%= link_to "Search More Artists", new_artist_path  %>
    <br/><%= link_to "Search Concerts for Similar Artists", new_concert_path  %>
  <% else %>
    <h1><%= @artist["artist"]["name"] %></h1>

    <span class="hidden-xs"><%= image_tag(@artist["artist"] ["image"][4]["#text"]) %></span>
    <span class="visible-xs visible-sm"><%= image_tag(@artist["artist"] ["image"][3]["#text"]) %></span>
    <br/>

    <% similar_name = @artist["artist"]["similar"].include?("artist") ? @artist["artist"]["similar"]["artist"][0]["name"] : " " %>
    <%= link_to "Add to My Artists", artists_path(artist: { name: @artist["artist"]["name"], photo: @artist["artist"]["image"][3]["#text"], similar: similar_name } ), 
        method: :post %>
    <% if @artist["artist"]["similar"].include?("artist") %>
      <h1>Similar Artists:</h1>
      <% @artist["artist"]["similar"]["artist"].each do |artist| %>
         <%= artist["name"] %><br/>
      <% end %>
    <% else %>
      <h1>Similar Artists: no similar artists listed at this moment.</h1>
    <% end %>
    <h1 class="hidden-xs"><%= @artist["artist"]["bio"]["summary"].html_safe %></h1>
  <% end %>
</div>

app/views/artists/new.html.erb
<img src="http://i.imgur.com/zCJezhy.jpg?1" id="bg-search2">
  <% provide(:title) %>
  <div class="jumbotron-artist text-center">
    <%= form_tag artists_path, :method => 'get' do %>
      <div class="search-tag">artist</div>
      <%= text_field_tag :artist, params[:artist] %><br /><br />
      <%= submit_tag "Search", class: "btn-concert btn-primary" %>
    <% end %>
  </div>

app/views/artists/show.html.erb
<img src="http://i.imgur.com/x2G2aLn.jpg" id="bg-list">
<% provide(:title, "My Artists") %>
<div id="saved-results text-center">
  <h1 class="header1">My Artists</h1><br/><br/>
  <% @my_artists.each do |artist| %>
    <%= artist.name %><br/><br/>
    <%= image_tag(artist.photo) %><br/>
    Similar Artists: <%= artist.similar %><br/><br/>
    <%= link_to 'Delete', artist_path(artist), method: :delete, data: { confirm: 'Are you sure?' } %><br/><br/>
    _____________________<br/><br/>
  <% end %>
</div>