config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  match '/home',       to: 'static_pages#home',    via: 'get'
  match '/about',      to: 'static_pages#about',   via: 'get'
  match '/signup',     to: 'users#new',            via: 'get'
  match '/signin',     to: 'sessions#new',         via: 'get'
  match '/signout',    to: 'sessions#destroy',     via: 'delete'
  match '/myconcerts', to: 'concerts#show',        via: 'get'
  match '/myartists',  to: 'artists#show',         via: 'get'

  
  resources :users,    only: [:create, :show]
  resources :artists,  only: [:new, :create, :index, :destroy]
  resources :sessions, only: [:create, :destroy]
  resources :concerts, only: [:new, :create, :index, :destroy]
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :artists, dependent: :destroy
  has_many :concerts, dependent: :destroy
  
  before_save { email.downcase! }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6, maximum:50 }

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def self.digest(token)
    Digest::MD5.hexdigest(token.to_s)
  end

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only:[:show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def new
     @user = User.new
  end

  def create
    @user =  User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to LVE! Start saving concerts to your profile!"
      sign_in @user
      redirect_back_or user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signed_in, notice: "Please sign in"
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/views/users/_form.html.erb
<div class="col-xs-12">
  <%= form_for(@user) do |form| %>
    <%= form.label :username, class: "form" %>:</br>
    <%= form.text_field :name, class: "input" %>
    </br>
    </br>
    <%= form.label :email_address, class: "form" %>:</br>  
    <%= form.text_field :email, class: "input" %>
    </br>
    </br>
    <%= form.label :password, class: "form" %>:</br>
    <%= form.password_field :password, class: "input" %>
    </br>
    </br>
    <%= form.label :confirmation, class: "form" %>:</br>
    <%= form.password_field :password_confirmation, class: "input" %>
    </br>
    </br>
    <%= form.submit 'Enter', class: "btn btn-primary" %>
    </br>
    </br>
    <a href="/signin">Already a member?</a>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="row text-center">
  <img src="http://i.imgur.com/UMAjFiA.jpg?4" id="bg-static">
    <% provide(:title, "Sign Up") %>  
  <div class="col-sm-12 col-sm-12 col-md-1 col-lg-1">
    <h1 class="sign-title join blink_me hidden-xs hidden-sm">Join</h1>
    <h1 class="xs-sign-title visible-xs">Join</h1>
  </div>
  <div class= "col-sm-12 col-md-11 col-lg-8">
    <div class="jumbotron user-form">
      <%= render 'form' %>
   </div>
  </div>
</div>

\

app/views/users/show.html.erb
<img src="http://i.imgur.com/WEPNSNd.jpg" id="bg-user">
<% provide(:title, @user.name) %>
<div class="row user-lve">
  <div class="col-xs-12">
    <h1 class="user-header">Let's get LVE <span class="hidden-xs"><%= @user.name %></span>...</h1>
  </div>
  </br>
  <div id="quick-links" class="col-xs-12 text-center hidden-xs">
    <button class="btn-search btn-primary search-links"><%= link_to "Concerts", new_concert_path %> </button>
    or
    <button class="btn-search btn-primary search-links"><%= link_to "Artists", new_artist_path %></button>
  </div>
  <div id="xs-quick-links" class="col-xs-12 text-center visible-xs">
    <button class="xs-btn-search btn-primary search-links"><%= link_to "Concerts", new_concert_path %> </button>
    or
    <button class="xs-btn-search btn-primary search-links"><%= link_to "Artists", new_artist_path %></button>
  </div>
</div>