config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  match '/home',       to: 'static_pages#home',    via: 'get'
  match '/about',      to: 'static_pages#about',   via: 'get'
  match '/signup',     to: 'users#new',            via: 'get'
  match '/signin',     to: 'sessions#new',         via: 'get'
  match '/signout',    to: 'sessions#destroy',     via: 'delete'
  match '/myconcerts', to: 'concerts#show',        via: 'get'
  match '/myartists',  to: 'artists#show',         via: 'get'

  
  resources :users,    only: [:create, :show]
  resources :artists,  only: [:new, :create, :index, :destroy]
  resources :sessions, only: [:create, :destroy]
  resources :concerts, only: [:new, :create, :index, :destroy]
  

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  belongs_to :user

  before_create :set_defaults

  # validates :performing_artists, presence: true 
  validates :user_id, presence: true

  def set_defaults
    self.concert_date       ||= "23/8/1988".to_date
    self.concert_time       ||= "TBD"
    self.venue              ||= "TBD"
    self.website            ||= "http://www.last.fm/"
    self.location           ||= "OuterSpace"
    self.performing_artists ||= "no opening acts"
    self.headliner          ||= self.performing_artists
  end

  def self.location(location)

    location = URI.encode(location)
 
    # auth = { query: { api_key: '0cf9f131e6c898341d48bf10b5488916' }} 
    search_url = "http://ws.audioscrobbler.com/2.0/?method=geo.getevents&location=#{location}&limit=50&api_key=0cf9f131e6c898341d48bf10b5488916&format=json"
    # search_url = "http://ws.audioscrobbler.com/2.0/?method=geo.getevents&location=#{location}&format=json"
    response = HTTParty.get search_url
    response["events"]["event"]
  end

  def self.artist(artist)
    
    artist = URI.encode(artist)

    auth = { query: { api_key: '0cf9f131e6c898341d48bf10b5488916' }} 
    search_url = "http://ws.audioscrobbler.com/2.0/?method=artist.getevents&artist=#{artist}&autocorrect[1]&format=json"
    response = HTTParty.get search_url, auth
    response["events"]["event"]
  end

  def self.both(artist, location)  
    
    location = URI.encode(location)
    
    auth = { query: { api_key: '0cf9f131e6c898341d48bf10b5488916' }} 
    search_url = "http://ws.audioscrobbler.com/2.0/?method=geo.getevents&location=#{location}&format=json"
    response = HTTParty.get search_url, auth
    
    response["events"]["event"].select do |event| 
      artists = Array(event["artists"]["artist"]).map { |artist| artist.downcase }
      artists.include?(artist)
    end         
  end

  def self.criteria(artist,location)
    return nil                        if artist.blank? && location.blank?
    return self.artist(artist)        if location.blank?
    return self.location(location)    if artist.blank?
    return self.both(artist,location)
  end    

end

app/controllers/concerts_controller.rb
  class ConcertsController < ApplicationController
  before_action :signed_in_user
  
  def new
    @concert = Concert.new
  end

  def show
    @my_concerts = current_user.concerts
  end

  def create
    @concert = current_user.concerts.build(concert_params)
    if @concert.save
      redirect_to myconcerts_path
    else
      render 'new'
    end
  end

  def index
    @concerts = Concert.criteria(params[:artist], params[:location])
    redirect_to new_concert_path if @concerts.nil?
  end

  def destroy
    @concert = Concert.find(params[:id])
    @concert.destroy
    redirect_to myconcerts_path, notice: "You have deleted a concert"
  end


  private

  def concert_params
    params.require(:concert).permit(:concert_date, :concert_time, :performing_artists, :venue, :website, :headliner, :location)
  end


  def signed_in_user
    redirect_to signin_path, notice: "Please sign in" unless signed_in?
  end

end 

app/helpers/concerts_helper.rb
module ConcertsHelper

  def show_date(event)
    event["startDate"].to_date
  end

  def add_to_concerts(event)
    link_to "Add to My Concerts", concerts_path(concert_params(event)), method: :post
  end

  def concert_params(event)
    { concert: { 
      headliner: event["artists"]["headliner"], performing_artists: event["artists"]["artist"].to_s, 
      location: event["venue"]["location"]["city"], venue: event["venue"]["name"], 
      concert_date: event["startDate"].to_date, website: event["url"]
    } }
  end
end

app/views/concerts/_results.html.erb
<table >
  <br/><% @concerts.each do |event| %> 
    <tr><h2><%= event["artists"]["headliner"] %></h2></tr>
    <br/>
    <tr><%= show_date(event) %></tr><br/></br>
    @ <tr><%= event["venue"]["name"] %><br/>
    in <%= event["venue"]["location"]["city"] %></tr><br/><br/>

    Featuring:<br/>
    <% Array(event["artists"]["artist"]).each do |artist| %>
      <tr><%= artist %></tr><br/>
    <% end %>

    <br/>
    <tr class="link"><%= link_to 'More info', event["url"] %></tr><br/><br/>
    <tr class><%= add_to_concerts(event) %></tr><br/>
    _____________________
  <% end %>
</table>  

app/views/concerts/index.html.erb
<img src="http://i.imgur.com/x2G2aLn.jpg" id="bg-results">
<% provide(:title, "Concert Results") %>
<div class="results">
  <%if Array(@concerts).count == 0 %>
    Sorry, there are no concerts listed for that criteria at this moment.</br> Check back later.</br> </br>  
    <br/><%= link_to "Search More Concerts", new_concert_path  %> OR 
    <%= link_to "Search Similar Artists Names", new_artist_path  %>
  <% else %>
    <table >
      <br/><% @concerts.each do |event| %> 
        <tr><h2><%= event["artists"]["headliner"] %></h2></tr>
        <br/>
        <tr><%= event["startDate"].to_date %></tr><br/></br>
        @ <tr><%= event["venue"]["name"] %><br/>
        in <%= event["venue"]["location"]["city"] %></tr><br/><br/>

        <%if event["artists"]["artist"].class == String %>
          <%= event["artists"]["artist"] %><br/>
        <% else %>
          Featuring:<br/>
          <% event["artists"]["artist"].each do |artist| %>
            <tr><%= artist %></tr><br/> 
          <% end %>
        <% end %>
    
        <br/>
        <tr class="link"><%= link_to 'More info', event["url"] %></tr><br/><br/>
        <tr class="link"><%= link_to "Add to My Concerts", concerts_path(concert: { headliner: event["artists"]["headliner"],   
        performing_artists: event["artists"]["artist"].to_s, location: event["venue"]["location"]["city"], 
        venue: event["venue"]["name"], concert_date: event["startDate"].to_date, website: event["url"]  }), 
        method: :post %></tr>
        <h1 class="hidden-md hidden-sm hidden-xs">________________________________________</h1>
        <h1 class="hidden-lg hidden-sm hidden-xs">_________________________</h1>
        <h1 class="hidden-lg hidden-md">___________</h1>
        <br/>
      <% end %> 
    </table>  
  <% end %>
</div>

app/views/concerts/new.html.erb
<img class="hidden-xs visible-lg-md-sm" src='https://i.imgur.com/Iwi1Vuz.jpg?4' id="bg-search">
<img class="visible-xs" src="http://i.imgur.com/iiUDpp6.jpg?2" id="bg-static">
<% provide(:title) %>

<div class="jumbotron search">
  <div id="search-params">
    <%= form_tag concerts_path, :method => 'get' do %>
      <div class="form-text">Concert Location:</div>
      <%= text_field_tag :location, params[:location] %>
      <div class="form-text">& Artist:</div>
      <%= text_field_tag :artist, params[:artist] %>
      </br>
      <%= submit_tag "Search", class: "btn-concert btn-primary" %> 
    <% end %>
  </div>
</div>

app/views/concerts/show.html.erb
<img src="https://i.imgur.com/x2G2aLn.jpg" id="bg-list">
<div id="saved-results">
  <% provide(:title, "My Concerts") %>
  <h1 class="header1">My Concerts</h1>  <br/>

  <h1><% @my_concerts.each do |concert| %></h1>
    <%= concert.headliner %><br/>
   
     <%= concert.concert_date %><br/>
    <%= concert.performing_artists.to_s %><br/>
    @<%= concert.venue %><br/>
    in <%= concert.location %><br/>
    <%= link_to 'More Info', concert.website.html_safe, target: "_blank" %><br/>
    <%= link_to 'Delete', concert_path(concert), method: :delete, data: { confirm: 'Are you sure you want to delete this concert?' } %><br/><br/>
    ---------------------------------<br/><br/>

  <% end %>
</div>