config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  match '/home',       to: 'static_pages#home',    via: 'get'
  match '/about',      to: 'static_pages#about',   via: 'get'
  match '/signup',     to: 'users#new',            via: 'get'
  match '/signin',     to: 'sessions#new',         via: 'get'
  match '/signout',    to: 'sessions#destroy',     via: 'delete'
  match '/myconcerts', to: 'concerts#show',        via: 'get'
  match '/myartists',  to: 'artists#show',         via: 'get'

  
  resources :users,    only: [:create, :show]
  resources :artists,  only: [:new, :create, :index, :destroy]
  resources :sessions, only: [:create, :destroy]
  resources :concerts, only: [:new, :create, :index, :destroy]
  

end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-fixed-bottom navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <p class="hidden-xs"><a id="amanda" href="http://www.linkedin.com/pub/amanda-raymond/8a/807/377/" target="_blank">Amanda Raymond</a></p>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> 
          <% if signed_in? %>
              <a class="nav navbar-nav" href="/concerts/new">Search Concerts</a>
              <a class="nav navbar-nav" href="/artists/new"> Search Artists</a>
            <% else %>
              <a class="nav navbar-nav" href="/about">LVE</a>
          <% end %>
        </li>
      </ul> 
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li class="linkster"><%= link_to "My Concerts", myconcerts_path %></li>
              <li class="linkster"><%= link_to "My Artist", myartists_path %></li>
              <li class="linkster"><%# link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li class="linkster"><%= link_to "About", about_path %></li>
              <li class="linkster"><%= link_to "Sign Out", signout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LVE | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body class="container-fluid">
    <div>
    <%= render 'layouts/navigation' %>  
    </div>    
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>  
  </body>
</html>